# Generated by Django 5.1.4 on 2025-02-15 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
