# Generated by Django 5.1.4 on 2025-02-15 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_student_user_alter_student_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
    ]
