# Generated by Django 5.1.4 on 2025-02-17 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0008_attendance'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='student',
            name='last_name',
        ),
        migrations.AddField(
            model_name='student',
            name='student',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
