# Generated by Django 5.1.4 on 2025-02-18 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0010_subject_student_class_name_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='credits',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(blank=True, choices=[('Present', 'Có mặt'), ('Absent', 'Vắng mặt')], max_length=10, null=True),
        ),
        migrations.DeleteModel(
            name='Grade',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
    ]
