# Generated by Django 5.1.4 on 2025-03-01 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0014_comment_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='fee',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='enrollment',
            name='fee_paid',
            field=models.DecimalField(decimal_places=2, default=1500.0, max_digits=10),
            preserve_default=False,
        ),
    ]
