# Generated by Django 5.1.4 on 2025-03-01 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0015_course_fee_enrollment_fee_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrollment',
            name='fee_paid',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
