# Generated by Django 5.1.4 on 2025-03-01 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0017_course_instructor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
