# Generated by Django 5.1.4 on 2025-03-01 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0018_remove_course_instructor_course_instructor_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='comment_files/'),
        ),
        migrations.AddField(
            model_name='comment',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='comment_images/'),
        ),
        migrations.AddField(
            model_name='forum',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='forum_files/'),
        ),
        migrations.AddField(
            model_name='forum',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='forum_images/'),
        ),
    ]
