# Generated by Django 5.1.4 on 2025-03-25 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0020_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='score',
        ),
        migrations.AddField(
            model_name='attendance',
            name='participation',
            field=models.CharField(blank=True, choices=[('Active', 'Học tích cực'), ('Inactive', 'Không tích cực')], max_length=20, null=True),
        ),
    ]
