# Generated by Django 5.1.4 on 2025-03-28 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0022_comment_likes_comment_updated_at'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
