# Generated by Django 5.1.4 on 2025-04-02 06:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0023_delete_teacher'),
        ('teachers', '0002_alter_teacher_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='instructor_name',
        ),
        migrations.AddField(
            model_name='course',
            name='instructor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teachers.teacher'),
        ),
    ]
